version: '3'

services:
  sdxl-benchmark:
    image: saladtechnologies/whisper-large-benchmark:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    environment:
      BENCHMARK_SIZE: -1
      REPORTING_URL: ${REPORTING_URL:-https://localhost:3000}
      REPORTING_API_KEY: ${REPORTING_API_KEY:-1234567890}
      QUEUE_URL: ${QUEUE_URL:-https://localhost:9324}
      BENCHMARK_NAME: whisper-large-benchmark-test
      QUEUE_NAME: ${QUEUE_NAME:-whisper-large-benchmark-test}
